//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product_Reviews
    {
        public int ReviewId { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Reviewer { get; set; }
        public string Comment { get; set; }
        public int ProductId { get; set; }
    
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
