//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ShippingDetail
    {
        public int ShippingDetailId { get; set; }
        public int ShippingId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Observation { get; set; }
    
        public virtual Tbl_Product Tbl_Product { get; set; }
        public virtual Tbl_Shipping Tbl_Shipping { get; set; }
    }
}
